#@author:  Arshia Zernab Hassan (hassa418@d.umn.edu)
#Create GLS network using data from GLS pipeline 
#Input: 
	#FDR matrix generated by GLS pipeline (.npy format)
	#sign matrix generated by GLS pipeline (.npy format)
	#all gene names from DepMap 2020 Q2 Achilles_gene_effect data
#Output: .Rdata matrix gls_in (GLS network) (.Rdata format)

library(RcppCNPy)

#load data generated by GLS pipeline (.npy format)
gls_in <- npyLoad("../data/20Q2_GLS_fdr.npy")
GLS_sign <- npyLoad("../data/20Q2_GLS_sign.npy")

#generate GLS network
gls_in <- 1 - gls_in
gls_in <- gls_in*GLS_sign
gls_in <- as.data.frame(gls_in)

#asign gene names as row and column names 
b <- read.csv("../data/all_genes_20q2.txt", sep = "\t", header = T)
colnames(gls_in)<-b$x
row.names(gls_in)<-b$x

#save GLS network (.Rdata)
save(gls_in,file ='../output/onion/gls_20q2_inv_sign_FDR.Rdata')
