#@author:  Arshia Zernab Hassan (hassa418@d.umn.edu)
#RPCA-normalization and evaluation: 
#Apply Robust Principal Component Analysis(RPCA) to create normalized data
#Evaluation with FLEX
#Input: 
	#DepMap 20q2 Achilles_gene_effect data preprocessed to replace NA values with gene-level mean (rows:genes, columns:cell lines)
#Output: 
	# Normalized data
	# Reconstructed data
	# PR plots
	# Diversity plots
	# Diversity data
	# AUPRC data

#rpca tool - https://cran.r-project.org/web/packages/rpca/index.html - rpca_0.2.3.tar.gz

library(stringi)
library(stringr)
library(rstudioapi)
library(desc)
library(withr)
library(ps)
library(usethis)
library(devtools)
library(RColorBrewer)

library(rpca)

# Function:
    # generate_stepwise_contribution_data
# Arguments:
    # complex_info : functional standard comparison result generated by FLEX::CalculatePredictionAndTrueOnLibraryProfiles()
	# data_complex_info : functional standard data(i.e. CORUM)  FLEX::data_complex
	# output_folder : output file path
	# output_file_name_noext : output file name postfix	
# Output: 
    # .pdf : diversity plot 
	# .tsv : diversity data
# Description:
    # Produce complex contribution diversity data and plot
generate_stepwise_contribution_data<-function(complex_info,data_complex_info, output_folder, output_file_name_noext)
{
  pairs_in <- data.frame(true = complex_info$true, 
                         predicted = complex_info$predicted, 
                         ID =  as.character(complex_info$ID), 
                         stringsAsFactors = FALSE)
  stepwise_contrib <- GenerateDataForPerfCurve(value.predicted = complex_info$predicted, 
                                               value.true = complex_info$true, 
                                               x.axis = 'TP', y.axis = 'precision')
  
  precision_cutoffs <- c(stepwise_contrib$y[length(stepwise_contrib$y)], seq(0.1, max(stepwise_contrib$y), 0.025)) #.1 0.025
  precision_cutoffs[1] <- round(precision_cutoffs[1], 4)
  
  stepwise_contrib <- GetStepwiseContributionOfEntities(pairs_in, precision_cutoffs, data_complex_info)
  stepwise_contrib_file <- paste('CORUM_complex_Diversity_data_',output_file_name_noext,'.tsv', sep = "")
  write.table(stepwise_contrib, stepwise_contrib_file, sep="\t", 
              col.names = TRUE, row.names = FALSE, quote = FALSE)
  
  stepwise_contrib <- stepwise_contrib[!duplicated(stepwise_contrib$Name), ]
  structure_plot_file <- paste('CORUM_complex_Diversity_plot_', output_file_name_noext, sep = "")
  PlotContributionStructure(stepwise_contrib, cutoff.all = precision_cutoffs, 
                            min.pairs = 10, outfile.name = structure_plot_file, outfile.type = 'pdf',
                            save.figure = TRUE)
  files <- c( 
    stepwise_contrib_file, paste(structure_plot_file, '.pdf', sep = "")
  )
  for (f in files)
  {
    file.copy(f, file.path(output_folder, f), overwrite = TRUE)
    file.remove(f)
  }
}

# Function:
    # generate_auprc_data
# Arguments:
    # complex_info : functional standard comparison result generated by FLEX::CalculatePredictionAndTrueOnLibraryProfiles()
	# data_complex_info : functional standard data(i.e. CORUM)  FLEX::data_complex
	# corum_info : functional standard alignments FLEX::MakeCoAnnotationFromGeneSymbols()
	# output_folder : output file path
	# output_file_name_noext : output file name postfix	
# Output: 
    # .txt : AUPRC data
# Description:
    # Produce AUPRC data
generate_auprc_data<-function(complex_info, data_complex_info, corum_info, output_folder, output_file_name_noext)
{
  complex_info$ID=as.character(complex_info$ID)
  complex_df <- as.data.frame(complex_info, stringsAsFactors = FALSE)
  data_AUPRC <- GetAreaUnderPRCurveForEntities (data_complex_info, corum_info, complex_df)
  auprc_file <- paste('Complex_AUPRC_',output_file_name_noext,'.txt', sep = "")
  write.table(data_AUPRC, auprc_file, sep = '\t', row.names = FALSE, quote = FALSE)
  files <- c( 
    auprc_file    
  )
  for (f in files)
  {
    file.copy(f, file.path(output_folder, f), overwrite = TRUE)
    file.remove(f)
  }
}

# Function:
    # generate_corum_similarity_plot
# Arguments:
    # corum_sim_list : list of standard comparison result generated by FLEX::CalculatePredictionAndTrueOnLibraryProfiles() 	
	# output_folder : output file path
	# output_file_name_noext : output file name
	# curve_names : list of curve names for legend annotation
	# cols : color list
	# title : title of plot 
# Output: 
    # pdf file (PR curve)
# Description:
    # Produce PR curve with given list of data
generate_corum_similarity_plot<-function(corum_sim_list, output_folder, output_file_name_noext, curve_names, cols, title)
{
  
  profile_similarity_plot <- paste(output_file_name_noext, 'CORUM_complex_PR_',  sep = "")
  labs <- c('TP', 'Precision')
  PlotPRSimilarity(corum_sim_list, outfile.name = profile_similarity_plot, 
                   outfile.type = 'pdf', fig.labs = labs, fig.title = title,
                   subsample = T,
                   legend.names = curve_names, 
                   legend.color = cols, save.figure = TRUE)
  
  files <- c( 
    paste(profile_similarity_plot, '.pdf', sep = "")
  )
  for (f in files)
  {
    file.copy(f, file.path(output_folder, f), overwrite = TRUE)
    file.remove(f)
  }
}


print("Loading data...")
#Load FLEX
#path to flex
flex_folder <- "../../FLEX"
#load flex package
load_all(flex_folder)
#generate CORUM standard alignments
corum <- MakeCoAnnotationFromGeneSymbols(data_standard = data_complex, overlap_length = 1,file_location = "corum")

output_folder <- "../output/rpca/"
file_ext <- "depmap_q2_2020_rpca_"

#load mitochondrial gene list
mito_gene_list_file_genes <- "../data/Mitochondial_genelist_1_26_2021_genes.tsv"
mito_data_genes <- read.csv(mito_gene_list_file_genes, sep = " ", header = F, stringsAsFactors = F)

print("Evaluating un-normalized data...")
#Load DepMap 20q2 Achilles_gene_effect data (NA values replaced with gene-level mean)
input_file_name <- "../data/depmap_q2_2020_nona_mean.tsv"
data <- read.csv(input_file_name, sep = "\t", header = TRUE, row.names = 1)

#create similarity network from un-normalized data
data_t <- data.frame(t(data)) #transpose data - genes as rows
sim_net <- cor(data_t, use = "all.obs",method="pearson") #use pearson correlation to create similarity network

print("Generating corum-complex standard evaluation data...")
#generate corum-complex standard evaluation results for un-normalized data
complex <- CalculatePredictionAndTrueOnLibraryProfiles(corum, sim_net)
corum_sim <- list(list(true = complex$true, predicted = complex$predicted))
corum_sim_projected <- list(list(true = complex$true, predicted = complex$predicted))

#curve name and color setting for un-normalized data PR curve
curve_labels <- c('Un-normalized')
col_set <- c()
cols0<-brewer.pal(4, "Dark2")
col_set <- c(cols0[4])

print("Generating diversity and AUPRC data...")
#generate diversity and AUPRC data for un-normalized data
layer = 0
stepwise_contribution_file_name_noext <- paste(file_ext,layer,sep = '')
generate_stepwise_contribution_data(complex, data_complex, output_folder, stepwise_contribution_file_name_noext)
auprc_file_name_noext <- paste(file_ext,layer,sep = '')
generate_auprc_data(complex, data_complex, corum, output_folder, auprc_file_name_noext)

print("Generating corum-complex standard evaluation data (no mito. gene pairs) ...")
#remove mitochondrial gene pairs
complex <- getSubsetOfCoAnnRemovePairs(corum, data.frame(complex), list(mito_data_genes$V1), replace = F)
corum_sim_no_mito <- list(list(true = complex$true, predicted = complex$predicted))


#color setting for PR curves
#cols1<-grey.colors(7)
cols1<- brewer.pal(n = 9, "BuGn")[5:7] #rpca
col_set <- c(col_set, cols1)

layer_list <-c(.7,.8,.9,1,1.1,1.2,1.3)
layer_list_2 <-c(.7,1,1.3)
for(layer in layer_list)
{
	print(layer)
  #generate normalized and reconstructed data
  # set RPCA lambda hyperparameter (suqre-root of maximum between row-number(genes) and column-number(cell-lines))
  lam  = layer/(sqrt(max(nrow(data),ncol(data))))
  print(lam)
  #scale data prior to applying rpca
  data <- scale(data)
  #apply rpca to original data
  pca <- rpca(data, lambda = lam)
  
  norm_data <- pca$S #Get RPCA-normalized data (variable S of rpca output contain sparse component or normlaized data)
  projected <- pca$L #Get RPCA-reconstructed data (variable L of rpca output contain low-rank component or reconstructed data)
  dimnames(norm_data) <- dimnames(data)
  dimnames(projected) <- dimnames(data)
  
  #save normalized and reconstructed data
  write.table(norm_data, file.path(output_folder, paste('normalized_pca_', layer,".tsv", sep = "")), sep = "\t",
              quote = FALSE, row.names = TRUE, col.names = TRUE)
  write.table(projected, file.path(output_folder, paste('projected_pca_', layer,".tsv", sep = "")), sep = "\t",
              quote = FALSE, row.names = TRUE, col.names = TRUE)
  
  print("Normalized data")
  print("Generating corum-complex standard evaluation data...")
  #create similarity network from normalized data
  norm_data_t <- data.frame(t(norm_data)) #transpose data - genes as rows
  sim_net <- cor(norm_data_t, use = "all.obs",method="pearson") #use pearson correlation to create similarity network
	#generate corum-complex standard evaluation results
  complex <- CalculatePredictionAndTrueOnLibraryProfiles(corum, sim_net)
  if(layer %in% layer_list_2){
	  corum_sim <- append(corum_sim, list(list(true = complex$true, predicted = complex$predicted)))
	  val = as.double(layer)*.007
	  label = bquote(paste(lambda,'=',.(val),sep = ''))
	  curve_labels <- c(curve_labels, label)
	  }
  
  print("Generating diversity and AUPRC data...")
  #generate diversity and AUPRC data
  stepwise_contribution_file_name_noext <- paste('normalized_',file_ext,layer,sep = '')
  generate_stepwise_contribution_data(complex, data_complex, output_folder, stepwise_contribution_file_name_noext)
  auprc_file_name_noext <- paste('normalized_',file_ext,layer,sep = '')
  generate_auprc_data(complex, data_complex, corum, output_folder, auprc_file_name_noext)
  
  if(layer %in% layer_list_2){
	  print("Generating corum-complex standard evaluation data no mito. ...")
	  #remove mitochondrial gene pairs
	  complex <- getSubsetOfCoAnnRemovePairs(corum, data.frame(complex), list(mito_data_genes$V1), replace = F)
	  corum_sim_no_mito <- append(corum_sim_no_mito, list(list(true = complex$true, predicted = complex$predicted))) 
	  }
  
  print("Projected data")
  print("Generating corum-complex standard evaluation data...")
  #create similarity network from projected data
  projected_t <- data.frame(t(projected)) #transpose data - genes as rows
  sim_net <- cor(projected_t, use = "all.obs",method="pearson") #use pearson correlation to create similarity network
  complex <- CalculatePredictionAndTrueOnLibraryProfiles(corum, sim_net)
  if(layer %in% layer_list_2){
	corum_sim_projected <- append(corum_sim_projected, list(list(true = complex$true, predicted = complex$predicted)))
	}
  print("Generating diversity data...")
  #generate diversity data
  stepwise_contribution_file_name_noext <- paste('projected_',file_ext,layer,sep = '')
  generate_stepwise_contribution_data(complex, data_complex, output_folder, stepwise_contribution_file_name_noext)

}

#generate PR curves of un-normalized data and normalized data
generate_corum_similarity_plot(corum_sim, output_folder, file_ext, curve_labels, col_set, "All gene pairs" )
#generate PR curves of un-normalized data and normalized data with mitochondrial genes removed
generate_corum_similarity_plot(corum_sim_no_mito, output_folder, paste(file_ext,'no_mito',sep=''), curve_labels, col_set, "No mito. gene pairs" )
#generate PR curves of un-normalized data and reconstructed data
generate_corum_similarity_plot(corum_sim_projected, output_folder, paste(file_ext,'projected',sep=''), curve_labels, col_set, "All gene pairs" )
